spring.application.name=activity-service
spring.config.import=optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}

# Activity Service Rate Limits
resilience4j.ratelimiter.instances.tracking.limitForPeriod=100
resilience4j.ratelimiter.instances.tracking.limitRefreshPeriod=1m
resilience4j.ratelimiter.instances.tracking.timeoutDuration=0s

resilience4j.ratelimiter.instances.fetching.limitForPeriod=100
resilience4j.ratelimiter.instances.fetching.limitRefreshPeriod=1m
resilience4j.ratelimiter.instances.fetching.timeoutDuration=0s