spring:
  application:
    name: gateway-service
  main:
    web-application-type: reactive
  cloud:
    config:
      import-check:
        enabled: false
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: ${USER_SERVICE_URI:lb://USER-SERVICE}
              predicates:
                - Path=/api/user/**
            - id: activity-service
              uri: ${ACTIVITY_SERVICE_URI:lb://ACTIVITY-SERVICE}
              predicates:
                - Path=/api/activities/**
            - id: ai-service
              uri: ${AI_SERVICE_URI:lb://AI-SERVICE}
              predicates:
                - Path=/api/recommendations/**
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://localhost:8180/realms/fitness-realm/protocol/openid-connect/certs}

server:
  port: ${PORT:8080}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
logging:
  level:
    root: DEBUG