spring.application.name=user-service
spring.config.import=optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}

# User Service Rate Limits
resilience4j.ratelimiter.instances.auth.limitForPeriod=100
resilience4j.ratelimiter.instances.auth.limitRefreshPeriod=1m
resilience4j.ratelimiter.instances.auth.timeoutDuration=0s

resilience4j.ratelimiter.instances.notes.limitForPeriod=100
resilience4j.ratelimiter.instances.notes.limitRefreshPeriod=1m
resilience4j.ratelimiter.instances.notes.timeoutDuration=0s