spring.application.name=activity-service

spring.mongodb.uri=mongodb://localhost:27017/fitness_activity_db

eureka.instance.prefer-ip-address=true
server.port = 8082
eureka.client.serviceUrl.defaultZone = http://localhost:8761/eureka/
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
kafka.topic.name = activity-events
logging.level.root = DEBUG

# Resilience4j Configuration
resilience4j.circuitbreaker.instances.userService.slidingWindowSize=10
resilience4j.circuitbreaker.instances.userService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.userService.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.userService.permittedNumberOfCallsInHalfOpenState=3

