
spring.application.name=configserver
# Set Config Server to Native Mode (Local files instead of Git)
spring.profiles.active=native

# Path where the configuration files are stored locally
spring.cloud.config.server.native.search-locations=classpath:/config
server.port = 8888